/**
 * Mock 데이터
 * 인턴 역량 리포트 프로토타입용 샘플 데이터
 */

import type {
  Intern,
  SkillScore,
  TeamAnalytics,
  SkillCategoryMeta,
  PositionMeta,
} from "@/types/intern";

/**
 * DiceBear Avataaars API를 사용하여 아바타 URL 생성
 * @param name - 인턴 이름 (시드로 사용)
 * @returns DiceBear API URL
 */
export const generateAvatarUrl = (name: string): string => {
  const seed = encodeURIComponent(name);
  return `https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}`;
};

/**
 * 역량 카테고리 메타데이터
 */
export const SKILL_CATEGORIES: SkillCategoryMeta[] = [
  {
    key: "technical",
    name: "기술 스킬",
    description: "프로그래밍 언어, 프레임워크, 도구 사용 능력",
  },
  {
    key: "project",
    name: "프로젝트 수행",
    description: "과제 완료율, 품질, 데드라인 준수",
  },
  {
    key: "collaboration",
    name: "협업",
    description: "팀워크, 코드 리뷰 참여도, 도움 주고받기",
  },
  {
    key: "communication",
    name: "커뮤니케이션",
    description: "의사소통 명확성, 문서화, 발표 능력",
  },
  {
    key: "problemSolving",
    name: "문제 해결",
    description: "디버깅, 창의적 해결책 도출, 분석 능력",
  },
  {
    key: "learning",
    name: "학습 능력",
    description: "새로운 기술 습득 속도, 자기주도 학습",
  },
  {
    key: "creativity",
    name: "창의성",
    description: "아이디어 제안, 혁신적 접근, UX/UI 감각",
  },
  {
    key: "professionalism",
    name: "전문성",
    description: "시간 관리, 책임감, 업무 태도",
  },
];

/**
 * 직무 메타데이터
 */
export const POSITIONS: PositionMeta[] = [
  { key: "frontend", name: "프론트엔드", color: "bg-blue-200" },
  { key: "backend", name: "백엔드", color: "bg-green-200" },
  { key: "designer", name: "디자이너", color: "bg-purple-200" },
  { key: "pm", name: "PM", color: "bg-orange-200" },
];

/**
 * 샘플 인턴 데이터
 */
export const mockInterns: Intern[] = [
  // 인턴 1: 김멋사 (프론트엔드, 고성장)
  {
    id: "1",
    name: "김멋사",
    email: "kim@likelion.org",
    avatarUrl: generateAvatarUrl("김멋사"),
    position: "frontend",
    cohort: 12,
    startDate: new Date("2025-01-08"),
    overallScore: 92,
    currentSkills: [
      { category: "technical", score: 94, previousScore: 86, trend: "up" },
      { category: "project", score: 88, previousScore: 80, trend: "up" },
      {
        category: "collaboration",
        score: 96,
        previousScore: 90,
        trend: "up",
      },
      {
        category: "communication",
        score: 90,
        previousScore: 81,
        trend: "up",
      },
      {
        category: "problemSolving",
        score: 93,
        previousScore: 87,
        trend: "up",
      },
      { category: "learning", score: 95, previousScore: 88, trend: "up" },
      { category: "creativity", score: 91, previousScore: 82, trend: "up" },
      {
        category: "professionalism",
        score: 89,
        previousScore: 80,
        trend: "up",
      },
    ],
    growthHistory: [
      {
        week: 1,
        date: new Date("2025-01-08"),
        overallScore: 60,
        skills: [
          { category: "technical", score: 60, trend: "stable" },
          { category: "project", score: 55, trend: "stable" },
          { category: "collaboration", score: 70, trend: "stable" },
          { category: "communication", score: 60, trend: "stable" },
          { category: "problemSolving", score: 65, trend: "stable" },
          { category: "learning", score: 70, trend: "stable" },
          { category: "creativity", score: 60, trend: "stable" },
          { category: "professionalism", score: 60, trend: "stable" },
        ],
        achievements: ["오리엔테이션 완료", "개발 환경 세팅 완료"],
      },
      {
        week: 2,
        date: new Date("2025-01-15"),
        overallScore: 65,
        skills: [
          { category: "technical", score: 65, previousScore: 60, trend: "up" },
          {
            category: "project",
            score: 60,
            previousScore: 55,
            trend: "up",
          },
          {
            category: "collaboration",
            score: 72,
            previousScore: 70,
            trend: "up",
          },
          {
            category: "communication",
            score: 62,
            previousScore: 60,
            trend: "up",
          },
          {
            category: "problemSolving",
            score: 67,
            previousScore: 65,
            trend: "up",
          },
          {
            category: "learning",
            score: 75,
            previousScore: 70,
            trend: "up",
          },
          {
            category: "creativity",
            score: 62,
            previousScore: 60,
            trend: "up",
          },
          {
            category: "professionalism",
            score: 63,
            previousScore: 60,
            trend: "up",
          },
        ],
        achievements: ["React 기초 학습 완료", "첫 컴포넌트 구현"],
      },
      {
        week: 3,
        date: new Date("2025-01-22"),
        overallScore: 72,
        skills: [
          { category: "technical", score: 72, previousScore: 65, trend: "up" },
          {
            category: "project",
            score: 68,
            previousScore: 60,
            trend: "up",
          },
          {
            category: "collaboration",
            score: 78,
            previousScore: 72,
            trend: "up",
          },
          {
            category: "communication",
            score: 70,
            previousScore: 62,
            trend: "up",
          },
          {
            category: "problemSolving",
            score: 75,
            previousScore: 67,
            trend: "up",
          },
          {
            category: "learning",
            score: 80,
            previousScore: 75,
            trend: "up",
          },
          {
            category: "creativity",
            score: 70,
            previousScore: 62,
            trend: "up",
          },
          {
            category: "professionalism",
            score: 70,
            previousScore: 63,
            trend: "up",
          },
        ],
        achievements: ["첫 프로젝트 완수", "코드 리뷰 참여 시작"],
      },
      {
        week: 4,
        date: new Date("2025-01-29"),
        overallScore: 77,
        skills: [
          { category: "technical", score: 78, previousScore: 72, trend: "up" },
          {
            category: "project",
            score: 73,
            previousScore: 68,
            trend: "up",
          },
          {
            category: "collaboration",
            score: 85,
            previousScore: 78,
            trend: "up",
          },
          {
            category: "communication",
            score: 74,
            previousScore: 70,
            trend: "up",
          },
          {
            category: "problemSolving",
            score: 80,
            previousScore: 75,
            trend: "up",
          },
          {
            category: "learning",
            score: 84,
            previousScore: 80,
            trend: "up",
          },
          {
            category: "creativity",
            score: 75,
            previousScore: 70,
            trend: "up",
          },
          {
            category: "professionalism",
            score: 75,
            previousScore: 70,
            trend: "up",
          },
        ],
        achievements: ["TypeScript 마스터", "팀원 도움 제공"],
      },
      {
        week: 5,
        date: new Date("2025-02-05"),
        overallScore: 81,
        skills: [
          { category: "technical", score: 82, previousScore: 78, trend: "up" },
          {
            category: "project",
            score: 76,
            previousScore: 73,
            trend: "up",
          },
          {
            category: "collaboration",
            score: 88,
            previousScore: 85,
            trend: "up",
          },
          {
            category: "communication",
            score: 77,
            previousScore: 74,
            trend: "up",
          },
          {
            category: "problemSolving",
            score: 84,
            previousScore: 80,
            trend: "up",
          },
          {
            category: "learning",
            score: 88,
            previousScore: 84,
            trend: "up",
          },
          {
            category: "creativity",
            score: 79,
            previousScore: 75,
            trend: "up",
          },
          {
            category: "professionalism",
            score: 78,
            previousScore: 75,
            trend: "up",
          },
        ],
        achievements: ["Next.js 프로젝트 주도", "멘토링 시작"],
      },
      {
        week: 6,
        date: new Date("2025-02-12"),
        overallScore: 84,
        skills: [
          { category: "technical", score: 85, previousScore: 82, trend: "up" },
          {
            category: "project",
            score: 78,
            previousScore: 76,
            trend: "up",
          },
          {
            category: "collaboration",
            score: 92,
            previousScore: 88,
            trend: "up",
          },
          {
            category: "communication",
            score: 80,
            previousScore: 77,
            trend: "up",
          },
          {
            category: "problemSolving",
            score: 86,
            previousScore: 84,
            trend: "up",
          },
          {
            category: "learning",
            score: 90,
            previousScore: 88,
            trend: "up",
          },
          {
            category: "creativity",
            score: 82,
            previousScore: 79,
            trend: "up",
          },
          {
            category: "professionalism",
            score: 79,
            previousScore: 78,
            trend: "up",
          },
        ],
        achievements: ["팀 프로젝트 리더", "기술 블로그 작성 시작"],
      },
      {
        week: 7,
        date: new Date("2025-02-19"),
        overallScore: 86,
        skills: [
          { category: "technical", score: 87, previousScore: 85, trend: "up" },
          {
            category: "project",
            score: 80,
            previousScore: 78,
            trend: "up",
          },
          {
            category: "collaboration",
            score: 93,
            previousScore: 92,
            trend: "up",
          },
          {
            category: "communication",
            score: 82,
            previousScore: 80,
            trend: "up",
          },
          {
            category: "problemSolving",
            score: 88,
            previousScore: 86,
            trend: "up",
          },
          {
            category: "learning",
            score: 91,
            previousScore: 90,
            trend: "up",
          },
          {
            category: "creativity",
            score: 84,
            previousScore: 82,
            trend: "up",
          },
          {
            category: "professionalism",
            score: 82,
            previousScore: 79,
            trend: "up",
          },
        ],
        achievements: ["API 설계 완료", "성능 최적화 기여"],
      },
      {
        week: 8,
        date: new Date("2025-02-26"),
        overallScore: 87,
        skills: [
          { category: "technical", score: 88, previousScore: 87, trend: "up" },
          {
            category: "project",
            score: 82,
            previousScore: 80,
            trend: "up",
          },
          {
            category: "collaboration",
            score: 94,
            previousScore: 93,
            trend: "up",
          },
          {
            category: "communication",
            score: 83,
            previousScore: 82,
            trend: "up",
          },
          {
            category: "problemSolving",
            score: 89,
            previousScore: 88,
            trend: "up",
          },
          {
            category: "learning",
            score: 92,
            previousScore: 91,
            trend: "up",
          },
          {
            category: "creativity",
            score: 85,
            previousScore: 84,
            trend: "up",
          },
          {
            category: "professionalism",
            score: 83,
            previousScore: 82,
            trend: "up",
          },
        ],
        achievements: ["중간 프로젝트 발표", "코드 리뷰어 인증"],
      },
      {
        week: 9,
        date: new Date("2025-03-04"),
        overallScore: 85,
        skills: [
          { category: "technical", score: 86, previousScore: 88, trend: "down" },
          {
            category: "project",
            score: 80,
            previousScore: 82,
            trend: "down",
          },
          {
            category: "collaboration",
            score: 90,
            previousScore: 94,
            trend: "down",
          },
          {
            category: "communication",
            score: 81,
            previousScore: 83,
            trend: "down",
          },
          {
            category: "problemSolving",
            score: 87,
            previousScore: 89,
            trend: "down",
          },
          {
            category: "learning",
            score: 88,
            previousScore: 92,
            trend: "down",
          },
          {
            category: "creativity",
            score: 82,
            previousScore: 85,
            trend: "down",
          },
          {
            category: "professionalism",
            score: 80,
            previousScore: 83,
            trend: "down",
          },
        ],
        achievements: ["기술 부채 해결"],
      },
      {
        week: 10,
        date: new Date("2024-05-11"),
        overallScore: 92,
        skills: [
          { category: "technical", score: 94, previousScore: 86, trend: "up" },
          {
            category: "project",
            score: 88,
            previousScore: 80,
            trend: "up",
          },
          {
            category: "collaboration",
            score: 96,
            previousScore: 90,
            trend: "up",
          },
          {
            category: "communication",
            score: 90,
            previousScore: 81,
            trend: "up",
          },
          {
            category: "problemSolving",
            score: 93,
            previousScore: 87,
            trend: "up",
          },
          {
            category: "learning",
            score: 95,
            previousScore: 88,
            trend: "up",
          },
          {
            category: "creativity",
            score: 91,
            previousScore: 82,
            trend: "up",
          },
          {
            category: "professionalism",
            score: 89,
            previousScore: 80,
            trend: "up",
          },
        ],
        achievements: ["최종 프로젝트 완성", "멘토링 시작", "MVP 인증"],
      },
    ],
    badges: [
      {
        id: "b1",
        type: "first_project",
        name: "첫 프로젝트 완수",
        description: "첫 프로젝트를 성공적으로 완료했습니다",
        iconUrl: "/badges/first-project.svg",
        earnedAt: new Date("2024-01-22"),
        rarity: "common",
      },
      {
        id: "b2",
        type: "team_player",
        name: "팀 플레이어",
        description: "뛰어난 협업 능력을 보여주었습니다",
        iconUrl: "/badges/team-player.svg",
        earnedAt: new Date("2024-02-05"),
        rarity: "rare",
      },
      {
        id: "b3",
        type: "fast_learner",
        name: "빠른 학습자",
        description: "새로운 기술을 빠르게 습득했습니다",
        iconUrl: "/badges/fast-learner.svg",
        earnedAt: new Date("2024-01-29"),
        rarity: "rare",
      },
      {
        id: "b4",
        type: "code_master",
        name: "코드 마스터",
        description: "우수한 코드 품질을 유지하고 있습니다",
        iconUrl: "/badges/code-master.svg",
        rarity: "epic",
      },
    ],
    milestones: [
      {
        id: "m1",
        title: "React 마스터",
        description: "React 관련 프로젝트 5개 완료",
        targetValue: 5,
        currentValue: 4,
        unit: "개",
        category: "technical",
        deadline: new Date("2024-06-30"),
      },
      {
        id: "m2",
        title: "코드 리뷰 전문가",
        description: "코드 리뷰 50회 참여",
        targetValue: 50,
        currentValue: 23,
        unit: "회",
        category: "collaboration",
        deadline: new Date("2024-06-30"),
      },
      {
        id: "m3",
        title: "완벽한 출석",
        description: "12주 연속 출석",
        targetValue: 12,
        currentValue: 6,
        unit: "주",
        category: "professionalism",
        deadline: new Date("2024-03-31"),
      },
    ],
    feedbacks: [
      {
        id: "f1",
        mentorName: "박멘토",
        mentorAvatar: "/avatars/mentor1.jpg",
        content:
          "코드 리뷰 시 적극적인 태도가 인상적입니다. 다른 팀원들에게도 좋은 영향을 주고 있어요.",
        category: "collaboration",
        rating: 5,
        createdAt: new Date("2024-02-10"),
      },
      {
        id: "f2",
        mentorName: "이멘토",
        mentorAvatar: "/avatars/mentor2.jpg",
        content:
          "TypeScript를 빠르게 습득하여 프로젝트에 바로 적용하는 모습이 훌륭합니다.",
        category: "learning",
        rating: 5,
        createdAt: new Date("2024-02-03"),
      },
      {
        id: "f3",
        mentorName: "박멘토",
        mentorAvatar: "/avatars/mentor1.jpg",
        content:
          "프로젝트 마감 기한을 더 여유있게 관리하면 좋을 것 같습니다. 시간 관리 스킬을 개선해보세요.",
        category: "professionalism",
        rating: 3,
        createdAt: new Date("2024-01-25"),
      },
    ],
    lastUpdated: new Date("2024-02-12"),
  },

  // 인턴 2: 이사자 (백엔드, 중간 성장)
  {
    id: "2",
    name: "이사자",
    email: "lee@likelion.org",
    avatarUrl: generateAvatarUrl("이사자"),
    position: "backend",
    cohort: 12,
    startDate: new Date("2024-01-08"),
    overallScore: 85,
    currentSkills: [
      { category: "technical", score: 95, previousScore: 90, trend: "up" },
      { category: "project", score: 83, previousScore: 76, trend: "up" },
      { category: "collaboration", score: 78, previousScore: 70, trend: "up" },
      { category: "communication", score: 76, previousScore: 68, trend: "up" },
      { category: "problemSolving", score: 90, previousScore: 84, trend: "up" },
      { category: "learning", score: 87, previousScore: 80, trend: "up" },
      { category: "creativity", score: 80, previousScore: 72, trend: "up" },
      { category: "professionalism", score: 85, previousScore: 78, trend: "up" },
    ],
    growthHistory: [
      {
        week: 1,
        date: new Date("2024-01-08"),
        overallScore: 65,
        skills: [
          { category: "technical", score: 75, trend: "stable" },
          { category: "project", score: 60, trend: "stable" },
          { category: "collaboration", score: 65, trend: "stable" },
          { category: "communication", score: 60, trend: "stable" },
          { category: "problemSolving", score: 70, trend: "stable" },
          { category: "learning", score: 65, trend: "stable" },
          { category: "creativity", score: 60, trend: "stable" },
          { category: "professionalism", score: 65, trend: "stable" },
        ],
        achievements: ["개발 환경 세팅", "Git 기초 학습"],
      },
      {
        week: 2,
        date: new Date("2024-01-15"),
        overallScore: 67,
        skills: [
          { category: "technical", score: 77, previousScore: 75, trend: "up" },
          { category: "project", score: 64, previousScore: 60, trend: "up" },
          { category: "collaboration", score: 66, previousScore: 65, trend: "up" },
          { category: "communication", score: 62, previousScore: 60, trend: "up" },
          { category: "problemSolving", score: 72, previousScore: 70, trend: "up" },
          { category: "learning", score: 67, previousScore: 65, trend: "up" },
          { category: "creativity", score: 62, previousScore: 60, trend: "up" },
          { category: "professionalism", score: 67, previousScore: 65, trend: "up" },
        ],
        achievements: ["Node.js 기초 학습"],
      },
      {
        week: 3,
        date: new Date("2024-01-22"),
        overallScore: 70,
        skills: [
          { category: "technical", score: 80, previousScore: 77, trend: "up" },
          { category: "project", score: 68, previousScore: 64, trend: "up" },
          { category: "collaboration", score: 68, previousScore: 66, trend: "up" },
          { category: "communication", score: 65, previousScore: 62, trend: "up" },
          { category: "problemSolving", score: 75, previousScore: 72, trend: "up" },
          { category: "learning", score: 70, previousScore: 67, trend: "up" },
          { category: "creativity", score: 65, previousScore: 62, trend: "up" },
          { category: "professionalism", score: 70, previousScore: 67, trend: "up" },
        ],
        achievements: ["Node.js API 구현", "데이터베이스 설계"],
      },
      {
        week: 4,
        date: new Date("2024-01-29"),
        overallScore: 72,
        skills: [
          { category: "technical", score: 82, previousScore: 80, trend: "up" },
          { category: "project", score: 70, previousScore: 68, trend: "up" },
          { category: "collaboration", score: 69, previousScore: 68, trend: "up" },
          { category: "communication", score: 66, previousScore: 65, trend: "up" },
          { category: "problemSolving", score: 77, previousScore: 75, trend: "up" },
          { category: "learning", score: 72, previousScore: 70, trend: "up" },
          { category: "creativity", score: 67, previousScore: 65, trend: "up" },
          { category: "professionalism", score: 73, previousScore: 70, trend: "up" },
        ],
        achievements: ["Express.js 마스터"],
      },
      {
        week: 5,
        date: new Date("2024-02-05"),
        overallScore: 74,
        skills: [
          { category: "technical", score: 85, previousScore: 82, trend: "up" },
          { category: "project", score: 73, previousScore: 70, trend: "up" },
          { category: "collaboration", score: 69, previousScore: 69, trend: "stable" },
          { category: "communication", score: 67, previousScore: 66, trend: "up" },
          { category: "problemSolving", score: 80, previousScore: 77, trend: "up" },
          { category: "learning", score: 75, previousScore: 72, trend: "up" },
          { category: "creativity", score: 68, previousScore: 67, trend: "up" },
          { category: "professionalism", score: 75, previousScore: 73, trend: "up" },
        ],
        achievements: ["PostgreSQL 최적화"],
      },
      {
        week: 6,
        date: new Date("2024-02-12"),
        overallScore: 76,
        skills: [
          { category: "technical", score: 88, previousScore: 85, trend: "up" },
          { category: "project", score: 75, previousScore: 73, trend: "up" },
          { category: "collaboration", score: 70, previousScore: 69, trend: "up" },
          { category: "communication", score: 68, previousScore: 67, trend: "up" },
          { category: "problemSolving", score: 82, previousScore: 80, trend: "up" },
          { category: "learning", score: 78, previousScore: 75, trend: "up" },
          { category: "creativity", score: 70, previousScore: 68, trend: "up" },
          { category: "professionalism", score: 77, previousScore: 75, trend: "up" },
        ],
        achievements: ["RESTful API 완성", "인증 시스템 구현"],
      },
      {
        week: 7,
        date: new Date("2024-02-19"),
        overallScore: 78,
        skills: [
          { category: "technical", score: 90, previousScore: 88, trend: "up" },
          { category: "project", score: 77, previousScore: 75, trend: "up" },
          { category: "collaboration", score: 71, previousScore: 70, trend: "up" },
          { category: "communication", score: 69, previousScore: 68, trend: "up" },
          { category: "problemSolving", score: 84, previousScore: 82, trend: "up" },
          { category: "learning", score: 80, previousScore: 78, trend: "up" },
          { category: "creativity", score: 72, previousScore: 70, trend: "up" },
          { category: "professionalism", score: 79, previousScore: 77, trend: "up" },
        ],
        achievements: ["GraphQL 도입"],
      },
      {
        week: 8,
        date: new Date("2024-02-26"),
        overallScore: 80,
        skills: [
          { category: "technical", score: 92, previousScore: 90, trend: "up" },
          { category: "project", score: 79, previousScore: 77, trend: "up" },
          { category: "collaboration", score: 72, previousScore: 71, trend: "up" },
          { category: "communication", score: 70, previousScore: 69, trend: "up" },
          { category: "problemSolving", score: 86, previousScore: 84, trend: "up" },
          { category: "learning", score: 82, previousScore: 80, trend: "up" },
          { category: "creativity", score: 74, previousScore: 72, trend: "up" },
          { category: "professionalism", score: 81, previousScore: 79, trend: "up" },
        ],
        achievements: ["마이크로서비스 설계"],
      },
      {
        week: 9,
        date: new Date("2024-03-04"),
        overallScore: 78,
        skills: [
          { category: "technical", score: 90, previousScore: 92, trend: "down" },
          { category: "project", score: 76, previousScore: 79, trend: "down" },
          { category: "collaboration", score: 70, previousScore: 72, trend: "down" },
          { category: "communication", score: 68, previousScore: 70, trend: "down" },
          { category: "problemSolving", score: 84, previousScore: 86, trend: "down" },
          { category: "learning", score: 80, previousScore: 82, trend: "down" },
          { category: "creativity", score: 72, previousScore: 74, trend: "down" },
          { category: "professionalism", score: 78, previousScore: 81, trend: "down" },
        ],
        achievements: ["리팩토링 완료"],
      },
      {
        week: 10,
        date: new Date("2024-03-11"),
        overallScore: 85,
        skills: [
          { category: "technical", score: 95, previousScore: 90, trend: "up" },
          { category: "project", score: 83, previousScore: 76, trend: "up" },
          { category: "collaboration", score: 78, previousScore: 70, trend: "up" },
          { category: "communication", score: 76, previousScore: 68, trend: "up" },
          { category: "problemSolving", score: 90, previousScore: 84, trend: "up" },
          { category: "learning", score: 87, previousScore: 80, trend: "up" },
          { category: "creativity", score: 80, previousScore: 72, trend: "up" },
          { category: "professionalism", score: 85, previousScore: 78, trend: "up" },
        ],
        achievements: ["프로젝트 최적화 완료", "문서화 우수상"],
      },
    ],
    badges: [
      {
        id: "b5",
        type: "first_project",
        name: "첫 프로젝트 완수",
        description: "첫 프로젝트를 성공적으로 완료했습니다",
        iconUrl: "/badges/first-project.svg",
        earnedAt: new Date("2024-01-25"),
        rarity: "common",
      },
      {
        id: "b6",
        type: "problem_solver",
        name: "문제 해결사",
        description: "복잡한 기술적 문제를 해결했습니다",
        iconUrl: "/badges/problem-solver.svg",
        earnedAt: new Date("2024-02-08"),
        rarity: "rare",
      },
      {
        id: "b7",
        type: "code_master",
        name: "코드 마스터",
        description: "우수한 코드 품질을 유지하고 있습니다",
        iconUrl: "/badges/code-master.svg",
        rarity: "epic",
      },
    ],
    milestones: [
      {
        id: "m4",
        title: "API 전문가",
        description: "RESTful API 10개 구현",
        targetValue: 10,
        currentValue: 5,
        unit: "개",
        category: "technical",
        deadline: new Date("2024-06-30"),
      },
      {
        id: "m5",
        title: "테스트 마스터",
        description: "단위 테스트 커버리지 80% 달성",
        targetValue: 80,
        currentValue: 45,
        unit: "%",
        category: "project",
        deadline: new Date("2024-05-31"),
      },
    ],
    feedbacks: [
      {
        id: "f4",
        mentorName: "최멘토",
        mentorAvatar: "/avatars/mentor3.jpg",
        content:
          "백엔드 기술에 대한 이해도가 뛰어납니다. 계속 이 방향으로 성장하세요!",
        category: "technical",
        rating: 5,
        createdAt: new Date("2024-02-10"),
      },
      {
        id: "f5",
        mentorName: "최멘토",
        mentorAvatar: "/avatars/mentor3.jpg",
        content: "팀 미팅에서 더 적극적으로 의견을 표현해보면 좋을 것 같아요.",
        category: "communication",
        rating: 3,
        createdAt: new Date("2024-02-01"),
      },
    ],
    lastUpdated: new Date("2024-02-12"),
  },

  // 인턴 3: 박디자 (디자이너, 안정적 성장)
  {
    id: "3",
    name: "박디자",
    email: "park@likelion.org",
    avatarUrl: generateAvatarUrl("박디자"),
    position: "designer",
    cohort: 12,
    startDate: new Date("2024-01-08"),
    overallScore: 91,
    currentSkills: [
      { category: "technical", score: 85, previousScore: 80, trend: "up" },
      { category: "project", score: 93, previousScore: 88, trend: "up" },
      { category: "collaboration", score: 95, previousScore: 90, trend: "up" },
      { category: "communication", score: 96, previousScore: 92, trend: "up" },
      { category: "problemSolving", score: 89, previousScore: 85, trend: "up" },
      { category: "learning", score: 86, previousScore: 82, trend: "up" },
      { category: "creativity", score: 98, previousScore: 93, trend: "up" },
      { category: "professionalism", score: 92, previousScore: 88, trend: "up" },
    ],
    growthHistory: [
      {
        week: 1,
        date: new Date("2024-01-08"),
        overallScore: 75,
        skills: [
          { category: "technical", score: 70, trend: "stable" },
          { category: "project", score: 75, trend: "stable" },
          { category: "collaboration", score: 80, trend: "stable" },
          { category: "communication", score: 85, trend: "stable" },
          { category: "problemSolving", score: 70, trend: "stable" },
          { category: "learning", score: 70, trend: "stable" },
          { category: "creativity", score: 85, trend: "stable" },
          { category: "professionalism", score: 80, trend: "stable" },
        ],
        achievements: ["Figma 작업 환경 구축", "디자인 시스템 학습"],
      },
      {
        week: 2,
        date: new Date("2024-01-15"),
        overallScore: 78,
        skills: [
          { category: "technical", score: 72, previousScore: 70, trend: "up" },
          { category: "project", score: 79, previousScore: 75, trend: "up" },
          { category: "collaboration", score: 83, previousScore: 80, trend: "up" },
          { category: "communication", score: 87, previousScore: 85, trend: "up" },
          { category: "problemSolving", score: 74, previousScore: 70, trend: "up" },
          { category: "learning", score: 72, previousScore: 70, trend: "up" },
          { category: "creativity", score: 87, previousScore: 85, trend: "up" },
          { category: "professionalism", score: 82, previousScore: 80, trend: "up" },
        ],
        achievements: ["컬러 팔레트 디자인"],
      },
      {
        week: 3,
        date: new Date("2024-01-22"),
        overallScore: 82,
        skills: [
          { category: "technical", score: 75, previousScore: 72, trend: "up" },
          { category: "project", score: 83, previousScore: 79, trend: "up" },
          { category: "collaboration", score: 87, previousScore: 83, trend: "up" },
          { category: "communication", score: 90, previousScore: 87, trend: "up" },
          { category: "problemSolving", score: 78, previousScore: 74, trend: "up" },
          { category: "learning", score: 75, previousScore: 72, trend: "up" },
          { category: "creativity", score: 90, previousScore: 87, trend: "up" },
          { category: "professionalism", score: 85, previousScore: 82, trend: "up" },
        ],
        achievements: ["첫 UI 디자인 완성", "사용자 리서치 수행"],
      },
      {
        week: 4,
        date: new Date("2024-01-29"),
        overallScore: 84,
        skills: [
          { category: "technical", score: 76, previousScore: 75, trend: "up" },
          { category: "project", score: 85, previousScore: 83, trend: "up" },
          { category: "collaboration", score: 89, previousScore: 87, trend: "up" },
          { category: "communication", score: 91, previousScore: 90, trend: "up" },
          { category: "problemSolving", score: 80, previousScore: 78, trend: "up" },
          { category: "learning", score: 77, previousScore: 75, trend: "up" },
          { category: "creativity", score: 92, previousScore: 90, trend: "up" },
          { category: "professionalism", score: 86, previousScore: 85, trend: "up" },
        ],
        achievements: ["UX 플로우 최적화"],
      },
      {
        week: 5,
        date: new Date("2024-02-05"),
        overallScore: 86,
        skills: [
          { category: "technical", score: 78, previousScore: 76, trend: "up" },
          { category: "project", score: 88, previousScore: 85, trend: "up" },
          { category: "collaboration", score: 90, previousScore: 89, trend: "up" },
          { category: "communication", score: 92, previousScore: 91, trend: "up" },
          { category: "problemSolving", score: 83, previousScore: 80, trend: "up" },
          { category: "learning", score: 80, previousScore: 77, trend: "up" },
          { category: "creativity", score: 93, previousScore: 92, trend: "up" },
          { category: "professionalism", score: 87, previousScore: 86, trend: "up" },
        ],
        achievements: ["반응형 디자인 완성"],
      },
      {
        week: 6,
        date: new Date("2024-02-12"),
        overallScore: 88,
        skills: [
          { category: "technical", score: 80, previousScore: 78, trend: "up" },
          { category: "project", score: 90, previousScore: 88, trend: "up" },
          { category: "collaboration", score: 92, previousScore: 90, trend: "up" },
          { category: "communication", score: 94, previousScore: 92, trend: "up" },
          { category: "problemSolving", score: 85, previousScore: 83, trend: "up" },
          { category: "learning", score: 82, previousScore: 80, trend: "up" },
          { category: "creativity", score: 95, previousScore: 93, trend: "up" },
          { category: "professionalism", score: 88, previousScore: 87, trend: "up" },
        ],
        achievements: ["디자인 시스템 구축", "프로토타입 제작"],
      },
      {
        week: 7,
        date: new Date("2024-02-19"),
        overallScore: 89,
        skills: [
          { category: "technical", score: 81, previousScore: 80, trend: "up" },
          { category: "project", score: 91, previousScore: 90, trend: "up" },
          { category: "collaboration", score: 93, previousScore: 92, trend: "up" },
          { category: "communication", score: 95, previousScore: 94, trend: "up" },
          { category: "problemSolving", score: 86, previousScore: 85, trend: "up" },
          { category: "learning", score: 83, previousScore: 82, trend: "up" },
          { category: "creativity", score: 96, previousScore: 95, trend: "up" },
          { category: "professionalism", score: 89, previousScore: 88, trend: "up" },
        ],
        achievements: ["애니메이션 디자인"],
      },
      {
        week: 8,
        date: new Date("2024-02-26"),
        overallScore: 90,
        skills: [
          { category: "technical", score: 82, previousScore: 81, trend: "up" },
          { category: "project", score: 92, previousScore: 91, trend: "up" },
          { category: "collaboration", score: 94, previousScore: 93, trend: "up" },
          { category: "communication", score: 95, previousScore: 95, trend: "stable" },
          { category: "problemSolving", score: 87, previousScore: 86, trend: "up" },
          { category: "learning", score: 84, previousScore: 83, trend: "up" },
          { category: "creativity", score: 97, previousScore: 96, trend: "up" },
          { category: "professionalism", score: 90, previousScore: 89, trend: "up" },
        ],
        achievements: ["사용자 테스트 완료"],
      },
      {
        week: 9,
        date: new Date("2024-03-04"),
        overallScore: 88,
        skills: [
          { category: "technical", score: 80, previousScore: 82, trend: "down" },
          { category: "project", score: 88, previousScore: 92, trend: "down" },
          { category: "collaboration", score: 90, previousScore: 94, trend: "down" },
          { category: "communication", score: 92, previousScore: 95, trend: "down" },
          { category: "problemSolving", score: 85, previousScore: 87, trend: "down" },
          { category: "learning", score: 82, previousScore: 84, trend: "down" },
          { category: "creativity", score: 93, previousScore: 97, trend: "down" },
          { category: "professionalism", score: 88, previousScore: 90, trend: "down" },
        ],
        achievements: ["디자인 가이드 문서화"],
      },
      {
        week: 10,
        date: new Date("2024-03-11"),
        overallScore: 91,
        skills: [
          { category: "technical", score: 85, previousScore: 80, trend: "up" },
          { category: "project", score: 93, previousScore: 88, trend: "up" },
          { category: "collaboration", score: 95, previousScore: 90, trend: "up" },
          { category: "communication", score: 96, previousScore: 92, trend: "up" },
          { category: "problemSolving", score: 89, previousScore: 85, trend: "up" },
          { category: "learning", score: 86, previousScore: 82, trend: "up" },
          { category: "creativity", score: 98, previousScore: 93, trend: "up" },
          { category: "professionalism", score: 92, previousScore: 88, trend: "up" },
        ],
        achievements: ["최종 프로젝트 디자인 완성", "UX상 수상"],
      },
    ],
    badges: [
      {
        id: "b8",
        type: "first_project",
        name: "첫 프로젝트 완수",
        description: "첫 프로젝트를 성공적으로 완료했습니다",
        iconUrl: "/badges/first-project.svg",
        earnedAt: new Date("2024-01-20"),
        rarity: "common",
      },
      {
        id: "b9",
        type: "design_wizard",
        name: "디자인 위저드",
        description: "탁월한 디자인 감각을 보여주었습니다",
        iconUrl: "/badges/design-wizard.svg",
        earnedAt: new Date("2024-02-01"),
        rarity: "epic",
      },
      {
        id: "b10",
        type: "team_player",
        name: "팀 플레이어",
        description: "뛰어난 협업 능력을 보여주었습니다",
        iconUrl: "/badges/team-player.svg",
        earnedAt: new Date("2024-02-10"),
        rarity: "rare",
      },
      {
        id: "b11",
        type: "communication_pro",
        name: "커뮤니케이션 전문가",
        description: "명확하고 효과적인 의사소통을 합니다",
        iconUrl: "/badges/communication-pro.svg",
        earnedAt: new Date("2024-02-08"),
        rarity: "rare",
      },
      {
        id: "b12",
        type: "mentor_choice",
        name: "멘토의 선택",
        description: "멘토가 선정한 우수 인턴입니다",
        iconUrl: "/badges/mentor-choice.svg",
        earnedAt: new Date("2024-02-12"),
        rarity: "legendary",
      },
    ],
    milestones: [
      {
        id: "m6",
        title: "UI/UX 전문가",
        description: "사용자 중심 디자인 프로젝트 8개 완료",
        targetValue: 8,
        currentValue: 6,
        unit: "개",
        category: "creativity",
        deadline: new Date("2024-06-30"),
      },
      {
        id: "m7",
        title: "완벽한 출석",
        description: "12주 연속 출석",
        targetValue: 12,
        currentValue: 6,
        unit: "주",
        category: "professionalism",
        completedAt: new Date("2024-02-12"),
      },
    ],
    feedbacks: [
      {
        id: "f6",
        mentorName: "정멘토",
        mentorAvatar: "/avatars/mentor4.jpg",
        content:
          "디자인 감각이 매우 뛰어나며, 사용자 경험에 대한 깊은 이해를 보여줍니다.",
        category: "creativity",
        rating: 5,
        createdAt: new Date("2024-02-11"),
      },
      {
        id: "f7",
        mentorName: "정멘토",
        mentorAvatar: "/avatars/mentor4.jpg",
        content: "팀원들과의 소통이 원활하고 피드백을 잘 수용합니다.",
        category: "communication",
        rating: 5,
        createdAt: new Date("2024-02-05"),
      },
    ],
    lastUpdated: new Date("2024-02-12"),
  },

  // 인턴 4: 정기획 (PM, 신규)
  {
    id: "4",
    name: "정기획",
    email: "jung@likelion.org",
    avatarUrl: generateAvatarUrl("정기획"),
    position: "pm",
    cohort: 13,
    startDate: new Date("2024-02-05"),
    overallScore: 80,
    currentSkills: [
      { category: "technical", score: 72, previousScore: 65, trend: "up" },
      { category: "project", score: 85, previousScore: 78, trend: "up" },
      { category: "collaboration", score: 88, previousScore: 82, trend: "up" },
      { category: "communication", score: 90, previousScore: 85, trend: "up" },
      { category: "problemSolving", score: 82, previousScore: 75, trend: "up" },
      { category: "learning", score: 77, previousScore: 70, trend: "up" },
      { category: "creativity", score: 80, previousScore: 73, trend: "up" },
      { category: "professionalism", score: 83, previousScore: 78, trend: "up" },
    ],
    growthHistory: [
      {
        week: 1,
        date: new Date("2024-02-05"),
        overallScore: 63,
        skills: [
          { category: "technical", score: 55, trend: "stable" },
          { category: "project", score: 65, trend: "stable" },
          { category: "collaboration", score: 68, trend: "stable" },
          { category: "communication", score: 70, trend: "stable" },
          { category: "problemSolving", score: 62, trend: "stable" },
          { category: "learning", score: 58, trend: "stable" },
          { category: "creativity", score: 60, trend: "stable" },
          { category: "professionalism", score: 65, trend: "stable" },
        ],
        achievements: ["PM 기초 교육 이수", "프로젝트 계획 수립"],
      },
      {
        week: 2,
        date: new Date("2024-02-12"),
        overallScore: 68,
        skills: [
          { category: "technical", score: 60, previousScore: 55, trend: "up" },
          { category: "project", score: 72, previousScore: 65, trend: "up" },
          { category: "collaboration", score: 75, previousScore: 68, trend: "up" },
          { category: "communication", score: 78, previousScore: 70, trend: "up" },
          { category: "problemSolving", score: 70, previousScore: 62, trend: "up" },
          { category: "learning", score: 65, previousScore: 58, trend: "up" },
          { category: "creativity", score: 68, previousScore: 60, trend: "up" },
          { category: "professionalism", score: 70, previousScore: 65, trend: "up" },
        ],
        achievements: ["첫 스프린트 계획", "이해관계자 미팅 주도"],
      },
      {
        week: 3,
        date: new Date("2024-02-19"),
        overallScore: 70,
        skills: [
          { category: "technical", score: 62, previousScore: 60, trend: "up" },
          { category: "project", score: 74, previousScore: 72, trend: "up" },
          { category: "collaboration", score: 77, previousScore: 75, trend: "up" },
          { category: "communication", score: 80, previousScore: 78, trend: "up" },
          { category: "problemSolving", score: 72, previousScore: 70, trend: "up" },
          { category: "learning", score: 67, previousScore: 65, trend: "up" },
          { category: "creativity", score: 70, previousScore: 68, trend: "up" },
          { category: "professionalism", score: 72, previousScore: 70, trend: "up" },
        ],
        achievements: ["백로그 정리"],
      },
      {
        week: 4,
        date: new Date("2024-02-26"),
        overallScore: 72,
        skills: [
          { category: "technical", score: 64, previousScore: 62, trend: "up" },
          { category: "project", score: 76, previousScore: 74, trend: "up" },
          { category: "collaboration", score: 79, previousScore: 77, trend: "up" },
          { category: "communication", score: 82, previousScore: 80, trend: "up" },
          { category: "problemSolving", score: 73, previousScore: 72, trend: "up" },
          { category: "learning", score: 69, previousScore: 67, trend: "up" },
          { category: "creativity", score: 72, previousScore: 70, trend: "up" },
          { category: "professionalism", score: 74, previousScore: 72, trend: "up" },
        ],
        achievements: ["로드맵 수립"],
      },
      {
        week: 5,
        date: new Date("2024-03-04"),
        overallScore: 74,
        skills: [
          { category: "technical", score: 66, previousScore: 64, trend: "up" },
          { category: "project", score: 78, previousScore: 76, trend: "up" },
          { category: "collaboration", score: 80, previousScore: 79, trend: "up" },
          { category: "communication", score: 84, previousScore: 82, trend: "up" },
          { category: "problemSolving", score: 74, previousScore: 73, trend: "up" },
          { category: "learning", score: 70, previousScore: 69, trend: "up" },
          { category: "creativity", score: 73, previousScore: 72, trend: "up" },
          { category: "professionalism", score: 76, previousScore: 74, trend: "up" },
        ],
        achievements: ["KPI 설정"],
      },
      {
        week: 6,
        date: new Date("2024-03-11"),
        overallScore: 76,
        skills: [
          { category: "technical", score: 68, previousScore: 66, trend: "up" },
          { category: "project", score: 80, previousScore: 78, trend: "up" },
          { category: "collaboration", score: 82, previousScore: 80, trend: "up" },
          { category: "communication", score: 86, previousScore: 84, trend: "up" },
          { category: "problemSolving", score: 76, previousScore: 74, trend: "up" },
          { category: "learning", score: 72, previousScore: 70, trend: "up" },
          { category: "creativity", score: 74, previousScore: 73, trend: "up" },
          { category: "professionalism", score: 78, previousScore: 76, trend: "up" },
        ],
        achievements: ["데이터 분석 완료"],
      },
      {
        week: 7,
        date: new Date("2024-03-18"),
        overallScore: 77,
        skills: [
          { category: "technical", score: 69, previousScore: 68, trend: "up" },
          { category: "project", score: 81, previousScore: 80, trend: "up" },
          { category: "collaboration", score: 83, previousScore: 82, trend: "up" },
          { category: "communication", score: 87, previousScore: 86, trend: "up" },
          { category: "problemSolving", score: 77, previousScore: 76, trend: "up" },
          { category: "learning", score: 73, previousScore: 72, trend: "up" },
          { category: "creativity", score: 75, previousScore: 74, trend: "up" },
          { category: "professionalism", score: 79, previousScore: 78, trend: "up" },
        ],
        achievements: ["프로세스 개선"],
      },
      {
        week: 8,
        date: new Date("2024-03-25"),
        overallScore: 78,
        skills: [
          { category: "technical", score: 70, previousScore: 69, trend: "up" },
          { category: "project", score: 82, previousScore: 81, trend: "up" },
          { category: "collaboration", score: 84, previousScore: 83, trend: "up" },
          { category: "communication", score: 88, previousScore: 87, trend: "up" },
          { category: "problemSolving", score: 78, previousScore: 77, trend: "up" },
          { category: "learning", score: 74, previousScore: 73, trend: "up" },
          { category: "creativity", score: 76, previousScore: 75, trend: "up" },
          { category: "professionalism", score: 80, previousScore: 79, trend: "up" },
        ],
        achievements: ["리스크 관리 완료"],
      },
      {
        week: 9,
        date: new Date("2024-04-01"),
        overallScore: 76,
        skills: [
          { category: "technical", score: 65, previousScore: 70, trend: "down" },
          { category: "project", score: 78, previousScore: 82, trend: "down" },
          { category: "collaboration", score: 82, previousScore: 84, trend: "down" },
          { category: "communication", score: 85, previousScore: 88, trend: "down" },
          { category: "problemSolving", score: 75, previousScore: 78, trend: "down" },
          { category: "learning", score: 70, previousScore: 74, trend: "down" },
          { category: "creativity", score: 73, previousScore: 76, trend: "down" },
          { category: "professionalism", score: 78, previousScore: 80, trend: "down" },
        ],
        achievements: ["중간 회고"],
      },
      {
        week: 10,
        date: new Date("2024-04-08"),
        overallScore: 80,
        skills: [
          { category: "technical", score: 72, previousScore: 65, trend: "up" },
          { category: "project", score: 85, previousScore: 78, trend: "up" },
          { category: "collaboration", score: 88, previousScore: 82, trend: "up" },
          { category: "communication", score: 90, previousScore: 85, trend: "up" },
          { category: "problemSolving", score: 82, previousScore: 75, trend: "up" },
          { category: "learning", score: 77, previousScore: 70, trend: "up" },
          { category: "creativity", score: 80, previousScore: 73, trend: "up" },
          { category: "professionalism", score: 83, previousScore: 78, trend: "up" },
        ],
        achievements: ["프로젝트 성공적 완료", "팀 리더십 인정"],
      },
    ],
    badges: [
      {
        id: "b13",
        type: "communication_pro",
        name: "커뮤니케이션 전문가",
        description: "명확하고 효과적인 의사소통을 합니다",
        iconUrl: "/badges/communication-pro.svg",
        earnedAt: new Date("2024-02-10"),
        rarity: "rare",
      },
      {
        id: "b14",
        type: "first_project",
        name: "첫 프로젝트 완수",
        description: "첫 프로젝트를 성공적으로 완료했습니다",
        iconUrl: "/badges/first-project.svg",
        rarity: "common",
      },
    ],
    milestones: [
      {
        id: "m8",
        title: "애자일 마스터",
        description: "스프린트 20회 진행",
        targetValue: 20,
        currentValue: 2,
        unit: "회",
        category: "project",
        deadline: new Date("2024-08-31"),
      },
    ],
    feedbacks: [
      {
        id: "f8",
        mentorName: "윤멘토",
        mentorAvatar: "/avatars/mentor5.jpg",
        content: "프로젝트 계획 수립 능력이 뛰어나며, 팀을 잘 이끌고 있습니다.",
        category: "project",
        rating: 4,
        createdAt: new Date("2024-02-12"),
      },
    ],
    lastUpdated: new Date("2024-02-12"),
  },

  // 인턴 5: 최코드 (프론트엔드, 초보)
  {
    id: "5",
    name: "최코드",
    email: "choi@likelion.org",
    avatarUrl: generateAvatarUrl("최코드"),
    position: "frontend",
    cohort: 13,
    startDate: new Date("2024-02-05"),
    overallScore: 75,
    currentSkills: [
      { category: "technical", score: 74, previousScore: 68, trend: "up" },
      { category: "project", score: 73, previousScore: 67, trend: "up" },
      { category: "collaboration", score: 78, previousScore: 72, trend: "up" },
      { category: "communication", score: 72, previousScore: 68, trend: "up" },
      { category: "problemSolving", score: 75, previousScore: 69, trend: "up" },
      { category: "learning", score: 82, previousScore: 75, trend: "up" },
      { category: "creativity", score: 74, previousScore: 68, trend: "up" },
      { category: "professionalism", score: 76, previousScore: 70, trend: "up" },
    ],
    growthHistory: [
      {
        week: 1,
        date: new Date("2024-02-05"),
        overallScore: 58,
        skills: [
          { category: "technical", score: 50, trend: "stable" },
          { category: "project", score: 55, trend: "stable" },
          { category: "collaboration", score: 60, trend: "stable" },
          { category: "communication", score: 58, trend: "stable" },
          { category: "problemSolving", score: 55, trend: "stable" },
          { category: "learning", score: 62, trend: "stable" },
          { category: "creativity", score: 58, trend: "stable" },
          { category: "professionalism", score: 60, trend: "stable" },
        ],
        achievements: ["개발 환경 세팅", "HTML/CSS 기초 복습"],
      },
      {
        week: 2,
        date: new Date("2024-02-12"),
        overallScore: 62,
        skills: [
          { category: "technical", score: 58, previousScore: 50, trend: "up" },
          { category: "project", score: 60, previousScore: 55, trend: "up" },
          { category: "collaboration", score: 65, previousScore: 60, trend: "up" },
          { category: "communication", score: 60, previousScore: 58, trend: "up" },
          { category: "problemSolving", score: 62, previousScore: 55, trend: "up" },
          { category: "learning", score: 68, previousScore: 62, trend: "up" },
          { category: "creativity", score: 62, previousScore: 58, trend: "up" },
          { category: "professionalism", score: 63, previousScore: 60, trend: "up" },
        ],
        achievements: ["JavaScript 기초 학습", "첫 웹페이지 제작"],
      },
      {
        week: 3,
        date: new Date("2024-02-19"),
        overallScore: 64,
        skills: [
          { category: "technical", score: 60, previousScore: 58, trend: "up" },
          { category: "project", score: 62, previousScore: 60, trend: "up" },
          { category: "collaboration", score: 67, previousScore: 65, trend: "up" },
          { category: "communication", score: 62, previousScore: 60, trend: "up" },
          { category: "problemSolving", score: 64, previousScore: 62, trend: "up" },
          { category: "learning", score: 70, previousScore: 68, trend: "up" },
          { category: "creativity", score: 64, previousScore: 62, trend: "up" },
          { category: "professionalism", score: 65, previousScore: 63, trend: "up" },
        ],
        achievements: ["React 입문"],
      },
      {
        week: 4,
        date: new Date("2024-02-26"),
        overallScore: 66,
        skills: [
          { category: "technical", score: 62, previousScore: 60, trend: "up" },
          { category: "project", score: 64, previousScore: 62, trend: "up" },
          { category: "collaboration", score: 69, previousScore: 67, trend: "up" },
          { category: "communication", score: 64, previousScore: 62, trend: "up" },
          { category: "problemSolving", score: 66, previousScore: 64, trend: "up" },
          { category: "learning", score: 72, previousScore: 70, trend: "up" },
          { category: "creativity", score: 66, previousScore: 64, trend: "up" },
          { category: "professionalism", score: 67, previousScore: 65, trend: "up" },
        ],
        achievements: ["컴포넌트 제작"],
      },
      {
        week: 5,
        date: new Date("2024-03-04"),
        overallScore: 68,
        skills: [
          { category: "technical", score: 64, previousScore: 62, trend: "up" },
          { category: "project", score: 66, previousScore: 64, trend: "up" },
          { category: "collaboration", score: 70, previousScore: 69, trend: "up" },
          { category: "communication", score: 66, previousScore: 64, trend: "up" },
          { category: "problemSolving", score: 68, previousScore: 66, trend: "up" },
          { category: "learning", score: 74, previousScore: 72, trend: "up" },
          { category: "creativity", score: 67, previousScore: 66, trend: "up" },
          { category: "professionalism", score: 69, previousScore: 67, trend: "up" },
        ],
        achievements: ["State 관리 학습"],
      },
      {
        week: 6,
        date: new Date("2024-03-11"),
        overallScore: 70,
        skills: [
          { category: "technical", score: 66, previousScore: 64, trend: "up" },
          { category: "project", score: 68, previousScore: 66, trend: "up" },
          { category: "collaboration", score: 72, previousScore: 70, trend: "up" },
          { category: "communication", score: 68, previousScore: 66, trend: "up" },
          { category: "problemSolving", score: 70, previousScore: 68, trend: "up" },
          { category: "learning", score: 76, previousScore: 74, trend: "up" },
          { category: "creativity", score: 69, previousScore: 67, trend: "up" },
          { category: "professionalism", score: 71, previousScore: 69, trend: "up" },
        ],
        achievements: ["API 연동 성공"],
      },
      {
        week: 7,
        date: new Date("2024-03-18"),
        overallScore: 72,
        skills: [
          { category: "technical", score: 68, previousScore: 66, trend: "up" },
          { category: "project", score: 70, previousScore: 68, trend: "up" },
          { category: "collaboration", score: 74, previousScore: 72, trend: "up" },
          { category: "communication", score: 70, previousScore: 68, trend: "up" },
          { category: "problemSolving", score: 72, previousScore: 70, trend: "up" },
          { category: "learning", score: 78, previousScore: 76, trend: "up" },
          { category: "creativity", score: 70, previousScore: 69, trend: "up" },
          { category: "professionalism", score: 73, previousScore: 71, trend: "up" },
        ],
        achievements: ["라우팅 구현"],
      },
      {
        week: 8,
        date: new Date("2024-03-25"),
        overallScore: 73,
        skills: [
          { category: "technical", score: 69, previousScore: 68, trend: "up" },
          { category: "project", score: 71, previousScore: 70, trend: "up" },
          { category: "collaboration", score: 75, previousScore: 74, trend: "up" },
          { category: "communication", score: 71, previousScore: 70, trend: "up" },
          { category: "problemSolving", score: 73, previousScore: 72, trend: "up" },
          { category: "learning", score: 79, previousScore: 78, trend: "up" },
          { category: "creativity", score: 71, previousScore: 70, trend: "up" },
          { category: "professionalism", score: 74, previousScore: 73, trend: "up" },
        ],
        achievements: ["폼 검증 완료"],
      },
      {
        week: 9,
        date: new Date("2024-04-01"),
        overallScore: 71,
        skills: [
          { category: "technical", score: 68, previousScore: 69, trend: "down" },
          { category: "project", score: 67, previousScore: 71, trend: "down" },
          { category: "collaboration", score: 72, previousScore: 75, trend: "down" },
          { category: "communication", score: 68, previousScore: 71, trend: "down" },
          { category: "problemSolving", score: 69, previousScore: 73, trend: "down" },
          { category: "learning", score: 75, previousScore: 79, trend: "down" },
          { category: "creativity", score: 68, previousScore: 71, trend: "down" },
          { category: "professionalism", score: 70, previousScore: 74, trend: "down" },
        ],
        achievements: ["중간 점검"],
      },
      {
        week: 10,
        date: new Date("2024-04-08"),
        overallScore: 75,
        skills: [
          { category: "technical", score: 74, previousScore: 68, trend: "up" },
          { category: "project", score: 73, previousScore: 67, trend: "up" },
          { category: "collaboration", score: 78, previousScore: 72, trend: "up" },
          { category: "communication", score: 72, previousScore: 68, trend: "up" },
          { category: "problemSolving", score: 75, previousScore: 69, trend: "up" },
          { category: "learning", score: 82, previousScore: 75, trend: "up" },
          { category: "creativity", score: 74, previousScore: 68, trend: "up" },
          { category: "professionalism", score: 76, previousScore: 70, trend: "up" },
        ],
        achievements: ["첫 프로젝트 완성", "빠른 성장 인정"],
      },
    ],
    badges: [
      {
        id: "b15",
        type: "fast_learner",
        name: "빠른 학습자",
        description: "새로운 기술을 빠르게 습득했습니다",
        iconUrl: "/badges/fast-learner.svg",
        earnedAt: new Date("2024-02-10"),
        rarity: "rare",
      },
      {
        id: "b16",
        type: "first_project",
        name: "첫 프로젝트 완수",
        description: "첫 프로젝트를 성공적으로 완료했습니다",
        iconUrl: "/badges/first-project.svg",
        rarity: "common",
      },
    ],
    milestones: [
      {
        id: "m9",
        title: "JavaScript 마스터",
        description: "JavaScript 심화 과정 완료",
        targetValue: 100,
        currentValue: 20,
        unit: "%",
        category: "technical",
        deadline: new Date("2024-05-31"),
      },
      {
        id: "m10",
        title: "프로젝트 완수",
        description: "개인 프로젝트 3개 완성",
        targetValue: 3,
        currentValue: 0,
        unit: "개",
        category: "project",
        deadline: new Date("2024-06-30"),
      },
    ],
    feedbacks: [
      {
        id: "f9",
        mentorName: "강멘토",
        mentorAvatar: "/avatars/mentor6.jpg",
        content:
          "학습 의욕이 높고 질문을 많이 하는 모습이 좋습니다. 계속 성장하세요!",
        category: "learning",
        rating: 4,
        createdAt: new Date("2024-02-11"),
      },
    ],
    lastUpdated: new Date("2024-02-12"),
  },
];

/**
 * 팀 통계 계산
 */
export const getTeamAnalytics = (): TeamAnalytics => {
  const totalInterns = mockInterns.length;
  const averageScore =
    mockInterns.reduce((sum, intern) => sum + intern.overallScore, 0) /
    totalInterns;

  const topPerformers = mockInterns
    .sort((a, b) => b.overallScore - a.overallScore)
    .slice(0, 5)
    .map((intern) => ({
      id: intern.id,
      name: intern.name,
      avatarUrl: intern.avatarUrl,
      overallScore: intern.overallScore,
      position: intern.position,
    }));

  // 역량별 팀 평균 계산
  const skillAverages: SkillScore[] = SKILL_CATEGORIES.map((skillMeta) => {
    const category = skillMeta.key;
    const scores = mockInterns.flatMap(
      (intern) =>
        intern.currentSkills.find((s) => s.category === category)?.score || 0
    );
    const avgScore = scores.reduce((sum, s) => sum + s, 0) / scores.length;

    return {
      category,
      score: Math.round(avgScore),
      trend: "stable" as const,
    };
  });

  // 주간 성장률 계산 (간단한 예시)
  const weeklyGrowthRate = 5.2; // 평균 5.2% 성장

  return {
    totalInterns,
    averageScore: Math.round(averageScore),
    topPerformers,
    skillAverages,
    weeklyGrowthRate,
  };
};

/**
 * ID로 인턴 찾기
 */
export const getInternById = (id: string): Intern | undefined => {
  return mockInterns.find((intern) => intern.id === id);
};

/**
 * 직무로 필터링
 */
export const getInternsByPosition = (position: string): Intern[] => {
  return mockInterns.filter((intern) => intern.position === position);
};

/**
 * 기수로 필터링
 */
export const getInternsByCohort = (cohort: number): Intern[] => {
  return mockInterns.filter((intern) => intern.cohort === cohort);
};
